apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: broker-certificate
  namespace: default
spec:
  dnsNames:
    - broker.med-united.health
  secretName: broker-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: broker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: vromero/activemq-artemis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8161
          env:
            - name: ARTEMIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: user
            - name: ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: password

---

kind: Service
apiVersion: v1
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
    - port: 8161

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: broker
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  tls:
    - hosts:
        - broker.med-united.health
      secretName: broker-tls
  rules:
    - host: broker.med-united.health
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: broker
                port:
                  number: 8161
