apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: broker-certificate
  namespace: default
spec:
  dnsNames:
    - broker.med-united.health
  secretName: broker-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: vromero/activemq-artemis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 61616
            - containerPort: 8161
          env:
            - name: ARTEMIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: user
            - name: ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: password
            - name: DISABLE_SECURITY
              value: "true"
          volumeMounts:
            - name: broker-data
              mountPath: /var/lib/artemis/data
      volumes:
        - name: broker-data
          configMap:
            name: broker-data
  volumeClaimTemplates:
    - metadata:
        name: broker-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "broker"
        resources:
          requests:
            storage: 1Gi

---

kind: Service
apiVersion: v1
metadata:
  name: broker-ui
spec:
  selector:
    app: broker
  ports:
    - name: dashboard
      port: 8161
      targetPort: 8161
      protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: broker-stomp
spec:
  selector:
    app: broker
  ports:
    - name: stomp
      port: 61616
      targetPort: 61616
      protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: broker
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  tls:
    - hosts:
        - broker.med-united.health
      secretName: broker-tls
  rules:
    - host: broker.med-united.health
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: broker-ui
                port:
                  number: 8161
          - path: /stomp
            pathType: Prefix
            backend:
              service:
                name: broker-stomp
                port:
                  number: 61616
